using BRIX.Library.Abilities;
using BRIX.Library.Aspects;
using BRIX.Library.Characters;
using BRIX.Library.DiceValue;
using BRIX.Library.Effects;
using BRIX.Utility.Extensions;
using Newtonsoft.Json;
using System.Net.Http.Json;
using System.Text.Json.Serialization;
