//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRIX.Web.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BRIX.Web.Client.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to your email with a link to activate your account..
        /// </summary>
        public static string Account_ConfirmationEmailWasSent {
            get {
                return ResourceManager.GetString("Account_ConfirmationEmailWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account confirmed successfully..
        /// </summary>
        public static string Account_ConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("Account_ConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something goes wrong when trying to confirm account..
        /// </summary>
        public static string Account_ConfirmFailed {
            get {
                return ResourceManager.GetString("Account_ConfirmFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Account_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend confirmation email.
        /// </summary>
        public static string Account_ResendConfirmationEmail {
            get {
                return ResourceManager.GetString("Account_ResendConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in.
        /// </summary>
        public static string Account_SignIn {
            get {
                return ResourceManager.GetString("Account_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in.
        /// </summary>
        public static string Account_SignInAction {
            get {
                return ResourceManager.GetString("Account_SignInAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is not correct..
        /// </summary>
        public static string Account_SignInFailed {
            get {
                return ResourceManager.GetString("Account_SignInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-up.
        /// </summary>
        public static string Account_SignUp {
            get {
                return ResourceManager.GetString("Account_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-up.
        /// </summary>
        public static string Account_SignUpAction {
            get {
                return ResourceManager.GetString("Account_SignUpAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Common_Characters {
            get {
                return ResourceManager.GetString("Common_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Common_Language {
            get {
                return ResourceManager.GetString("Common_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid..
        /// </summary>
        public static string Validation_EmailFormat {
            get {
                return ResourceManager.GetString("Validation_EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email field is required..
        /// </summary>
        public static string Validation_EmailRequired {
            get {
                return ResourceManager.GetString("Validation_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string Validation_PasswordConfirmCompare {
            get {
                return ResourceManager.GetString("Validation_PasswordConfirmCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string Validation_PasswordLength {
            get {
                return ResourceManager.GetString("Validation_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is required..
        /// </summary>
        public static string Validation_PasswordRequired {
            get {
                return ResourceManager.GetString("Validation_PasswordRequired", resourceCulture);
            }
        }
    }
}
